# Generated by Django 3.2.6 on 2022-09-15 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimetable',
            name='course_unit_code',
        ),
        migrations.RemoveField(
            model_name='classtimetable',
            name='course_unit_lecturer',
        ),
        migrations.RemoveField(
            model_name='classtimetable',
            name='course_unit_name',
        ),
        migrations.RemoveField(
            model_name='classtimetable',
            name='days_of_the_week',
        ),
        migrations.RemoveField(
            model_name='classtimetable',
            name='time_of_class',
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='file_uploaded',
            field=models.FileField(default=django.utils.timezone.now, upload_to='class_timetables/'),
            preserve_default=False,
        ),
    ]
